export default [
    { sourceUnit: 'meter', targetUnit: 'decimeter', factor: '10' },
    { sourceUnit: 'meter', targetUnit: 'centimeter', factor: '100' },
    { sourceUnit: 'meter', targetUnit: 'millimeter', factor: '1000' },
    { sourceUnit: 'meter', targetUnit: 'kilometer', factor: '0.001' },
    { sourceUnit: 'meter', targetUnit: 'foot', factor: '3.28084' },
    { sourceUnit: 'foot', targetUnit: 'inch', factor: '12' },
    { sourceUnit: 'yard', targetUnit: 'foot', factor: '3' },
    { sourceUnit: 'mile', targetUnit: 'yard', factor: '1760' },
    { sourceUnit: 'minute', targetUnit: 'second', factor: '60' },
    { sourceUnit: 'hour', targetUnit: 'minute', factor: '60' },
    { sourceUnit: 'day', targetUnit: 'hour', factor: '24' },
    { sourceUnit: 'week', targetUnit: 'day', factor: '7' },
    { sourceUnit: 'year', targetUnit: 'day', factor: '365' },
    { sourceUnit: 'gram', targetUnit: 'milligram', factor: '1000' },
    { sourceUnit: 'kilogram', targetUnit: 'gram', factor: '1000' },
    { sourceUnit: 'tonne', targetUnit: 'kilogram', factor: '1000' },
    { sourceUnit: 'ounce', targetUnit: 'gram', factor: '28.3495' },
    { sourceUnit: 'pound', targetUnit: 'ounce', factor: '16' },
    { sourceUnit: 'ton', targetUnit: 'pound', factor: '2000' },
    { sourceUnit: 'liter', targetUnit: 'quart', factor: '1.056710' },
    { sourceUnit: 'gallon', targetUnit: 'quart', factor: '4' },
];
